### ISSUE TITLE
Super Sonic doesn't have unique sprites

### ISSUE THREAD

**Issue by starleaf-luna** [RetroKoH/S1Fixed#34]
Super Sonic still has his usual Sonic sprites, not his Super Sonic sprites from Sonic 2. this is unexpected, but I think it should be easy to solve when the assets are ready. I'd be happy to provide the code changes required!
![obraz](https://github.com/user-attachments/assets/a5ae2858-ec7e-42f9-9ab0-fdd3ccb20bb9)

**Comment by RetroKoH** [comment]
I've got the code handled just fine. Sprites are incoming! Cheers for the notification though. If you notice anything bugged, please lemme know. Spamming Jump to transform apparently breaks things, so that's on the docket to be fixed.

**Comment by starleaf-luna** [comment]
ah, nice to hear an update! it's great the sprites are incoming!

**Comment by RetroKoH** [comment]
Yes, please don't worry. Updates are halted temporarily because I'm documenting all changes in the wiki for posterity (and double-checking code for efficiency in the process). I spent most of today actively fleshing out the to-do list for the next release, and finishing Super Sonic is at the top of the list.
